rg1                      = "azadorg"
rg_location              = "West Europe"
account_replication_type = "LRS"
account_tier             = "Standard"
storage_account_name     = "azadostg"
rg2 = "azadorg2"
rg3 = "azadorg3"
rg5 = "azadorg5"